# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constituency', models.CharField(max_length=200)),
                ('constituency_code', models.IntegerField()),
                ('leading_candidate', models.CharField(max_length=200)),
                ('leading_party', models.CharField(max_length=200)),
                ('trailing_candidate', models.CharField(max_length=200)),
                ('trailing_party', models.CharField(max_length=200)),
                ('margin', models.IntegerField()),
                ('status', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('state_code', models.CharField(max_length=100)),
            ],
        ),
    ]
